---
title: "Analyzing NHL Data from 2007-2008 to 2018-2019"
format: 
  html:
    theme: cosmo  # zephyr pulse, sketchy, default, cosmo, vapor etc
author:
  - name: Coby Darer
    email: darerjf@appstate.edu
    affiliation:
      - name: Appalachian State University
        city: Boone
        state: NC  
        url: https://www.appstate.edu/
abstract: >
  This project will explore 5 v 5 data on NHL teams and players from the 2007-2008 season to the 2018-2019 season.
---
## Loading the Necessary Packages
```{r}
#| message: false
library(nhldata)
library(dplyr)
library(lubridate)
library(tidyr)
library(ggplot2)
```
## Exploring some data on skaters
```{r}
glimpse(skaters)
```

```{r}
#| code-fold: true
skaters %>%
  filter(p >= 50) %>%
  ggplot(aes(x = season)) +
    geom_bar(color = "black", fill = "lightblue") +
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90))
```

```{r}
#| code-fold: true
skaters %>%
  filter(ish_pct >= 20) %>%
  ggplot(aes(x = season)) +
  geom_bar(color = "black", fill = "lightblue") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))

skaters %>%
  filter(ish_pct >= 10) %>%
  ggplot(aes(x = season)) +
  geom_bar(color = "black", fill = "lightblue") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))
```
## Exploring some data on each team
```{r}
glimpse(teams)
```

```{r}
#| code-fold: true
West_conf <- teams %>%
  filter(team %in% c("ANA", "ARI", "CGY", "CHI", "COL", "DAL", "EDM", "LA", "MIN", "NSH", "SJ", "STL", "VAN"))

East_conf <- teams %>%
  filter(team %in% c("BOS", "BUF", "CAR", "CBJ", "DET", "FLA", "MTL", "NJ", "NYI", "NYR", "OTT", "PHI", "PIT", "TB", "TOR", "WSH"))

Atlantic_div <- East_conf %>%
  filter(team %in% c("BOS", "BUF", "DET", "FLA", "MTL", "OTT", "TB", "TOR"))

Metro_div <- East_conf %>%
  filter(team %in% c("CAR", "CBJ", "NJ", "NYI", "NYR", "PHI", "PIT", "WSH"))

Central_div <- West_conf %>%
  filter(team %in% c("ARI", "CHI", "COL", "DAL", "MIN", "NSH", "STL"))

Pacific_div <- West_conf %>%
  filter(team %in% c("ANA", "CGY", "EDM", "LA", "SJ", "VAN"))

```

```{r}
#| code-fold: true
#| warning: false
#| message: false
Central_div %>%
  filter(season != "2012-2013") %>%
  ggplot(aes(x = season, y = gf, color = team)) + 
    geom_point() +
    geom_line(aes(group = team)) +
    geom_smooth(aes(group = 1), se = FALSE) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90))

Pacific_div %>%
  filter(season != "2012-2013") %>%
  ggplot(aes(x = season, y = gf, color = team)) + 
    geom_point() +
    geom_line(aes(group = team)) +
    geom_smooth(aes(group = 1), se = FALSE) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90))

Atlantic_div %>%
  filter(season != "2012-2013") %>%
  ggplot(aes(x = season, y = gf, color = team)) + 
    geom_point() +
    geom_line(aes(group = team)) +
    geom_smooth(aes(group = 1), se = FALSE) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90))

Metro_div %>%
  filter(season != "2012-2013") %>%
  ggplot(aes(x = season, y = gf, color = team)) + 
    geom_point() +
    geom_line(aes(group = team)) +
    geom_smooth(aes(group = 1), se = FALSE) + 
    theme_bw() + 
    theme(axis.text.x = element_text(angle = 90))
```
## Exploring some data on goalies
```{r}
glimpse(goalies)
```

```{r}
goalies %>%
  filter(sv_pct >= 91.00) %>%
  filter(gp >= 45) %>%
  ggplot(aes(x = season)) + 
  geom_bar(color = "black", fill = "lightblue") + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90))
```

