project:
  type: website
  output-dir: docs

website:
  title: "Coby Darer"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - education.qmd
      - experience.qmd
      - project.qmd
      - href: skills.qmd
        text: Technical Skills
      - href: Resume.pdf
        text: Resume
    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/cobydarer
      - icon: github
        href: https://github.com/cobydarer
        
format:
  html:
    theme: zephyr  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

